version: "3.2"
services:
  node:
    build:
      context: .
    user: "node"
    working_dir: /home/node/
    environment:
      - NODE_ENV=production
    expose:
      - "8001"
    command: "npm start"