version: "3.2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/
    environment:
      - NODE_ENV=production
    volumes:
      - /var/jenkins_home/workspace/nodejs/nodejs-example/:/home/node/
    expose:
      - "8001"
    command: "npm start"